//Function to get a players bet of between $5 and $10
var prompt = require('prompt-sync')();
var colors = require('colors');

function getBet(){
  var bet = prompt("Please place a bet between $5 and $10 for your guess: ");
  if (checkBet(bet)){
    return bet;
  } else {
    getBet()
  }
}
//Helper function to getBet() to verify that user input is between 5 and 10
function checkBet(bet){
  if ((bet < 5) || (bet > 10)){
    console.log("Your bet must be between $5 and $10. Try again.".red);
    return false;
  }else {
    return true;
  }
}
//Function to get a players guess of between 1 and 10
function getGuess(){
  var guess = prompt("Please pick a number between 1 and 10: ");
  if (checkGuess(guess)){
    return guess;
  } else {
    getGuess();
  }
}
//Helper function to getGuess to verify that a user input is between 1 and 10
function checkGuess(guess){
  if ((guess < 1) || (guess > 10)){
    console.log("Your guess must be between 1 and 10. Try again.".red)
    return false;
  }else {
    return true;
  }
}
//Generate and return a random number between 1 and 10
function getRandom(){
  return 1 + Math.floor(Math.random()*10);
}
//Return the difference between two numbers
function checkDiff(compNum, playerNum){
  return compNum - playerNum;
}
//Game-specific function to perform specific behaviour depending on variables diff bet and bankroll
//If the diff is 0, the user has made the correct guess and bankroll increases by value of bet
//If diff is 1, nothing happens
//Otherwise, players bankroll decreases by bet
function getOutcome(diff, bet, bankroll){
  console.log("Results from this round".rainbow);
  if (diff===0){
    bankroll += +bet;
    var message = "Correct! You win this round.".green;
    console.log(message);
  }
  else if (Math.abs(diff) === 1){
    var message = "You were within exactly 1 of the actual number. Nothing happens.".yellow;
    console.log(message);
  }
  else{
    bankroll -= bet;
    var message = "Too bad! You lost this round.".red;
    console.log(message);
  }
  return bankroll;
}

//Alert user with bankroll amount
function getStatus(bankroll){
  console.log("Your current bankroll is: ".green + bankroll);
}

//Alert user with their guess, and the number generated by the computer
function getRoundStats(playerNum, compNum){
  console.log("Your guess was: " + playerNum + '\n' + "The computer's number was: " + compNum);
}

//Verify that the users repsonse to whether or not they want to continue playing is with 'y' or 'n'
function checkResponse(answer){
  if ((answer.toLowerCase()) === 'n' || (answer.toLowerCase() === 'y')){
    return true;
  }
  else{
    return false;
  }
}

//Function to verify whether or not a user would like to continue playing
function getContinuePlaying(){
  var answer = prompt("Would you like to continue playing?: (y/n)".magenta)
  if (checkResponse(answer)){
    if (answer.toLowerCase() === 'n'){
      return false;
    }
    else{
      return true;
    }
  }
  else{
    console.log("Please provide a y/n response!").red;
    getContinuePlaying();
  }
}

//Function to execute all game

function getPlayerData(){
  var playerData = {};
  var playerNum = prompt("Please enter your guess: ");
  var playerBet = prompt("Please enter your bet: ");
  playerData.playerNum = playerNum;
  playerData.playerBet = playerBet;
  return playerData;
}

function getBeginStatus(bankroll){
  console.log("Your starting bankroll is: ".green + bankroll);
}

function getFinalStatus(bankroll){
  if (bankroll < 0){
    bankroll = 0;
  }
  console.log("Your ending bankroll is: ".green + bankroll);
}

function runGame(bankroll){
  if (bankroll > 0){
    playerData = getPlayerData();
    playerNum = playerData.playerNum;
    playerBet = playerData.playerBet;
    if (checkBet(playerBet) && checkGuess(playerNum)){
      getBeginStatus(bankroll);
      var compNum = getRandom();
      var diff = checkDiff(compNum, playerNum);
      bankroll = getOutcome(diff, playerBet, bankroll);
      getRoundStats(playerNum, compNum);
      getFinalStatus(bankroll);
    }
    if (getContinuePlaying()){
      runGame(bankroll);
    }
  }
  console.log("Thanks for playing!".green);
}


runGame(100);
